[versions]
# Java and Kotlin
java = "17"
kotlin = "2.0.0"

# Minecraft/Forge
minecraft = "1.20.1"
forge = "47.4.9"
parchment = "2023.09.03"

# Plugins
neoforged_legacyforge = "2.0.124"
modrinth_minotaur = "2.+"

# Libraries
kotlinforforge = "4.11.0"

# Dependencies
cc = "1.113.1"
cache2k = "2.6.1.Final"

[libraries]
kotlinforforge = { module = "thedarkcolour:kotlinforforge", version.ref = "kotlinforforge" }

cc-core = { module = "cc.tweaked:cc-tweaked-1.20.1-core", version.ref = "cc" }
cc-api-core = { module = "cc.tweaked:cc-tweaked-1.20.1-core-api", version.ref = "cc" }
cc-api-forge = { module = "cc.tweaked:cc-tweaked-1.20.1-forge-api", version.ref = "cc" }
cc-runtime = { module = "cc.tweaked:cc-tweaked-1.20.1-forge", version.ref = "cc" }

[plugins]
neoforged-legacyforge = { id = "net.neoforged.moddev.legacyforge", version.ref = "neoforged_legacyforge" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
modrinth-minotaur = { id = "com.modrinth.minotaur", version.ref = "modrinth_minotaur" }
